// Address PR Comments Chat workflow.
//
// Interactive chat about the proposed fix plan generated by the
// `analyze_pr_comments` workflow. The engineer can ask the model to revise a
// proposed fix, explain its reasoning, or describe an alternative approach.
// Streams reply tokens live to the frontend.

import { z } from "zod";
import { ChatHistoryItemSchema } from "./chat-with-tools.js";

export const AddressPrChatInputSchema = z.object({
  contextText: z.string(),
  historyJson: z.string(),
});

export type AddressPrChatInput = z.infer<typeof AddressPrChatInputSchema>;

export const AddressPrChatHistorySchema = z.array(ChatHistoryItemSchema);

export function buildAddressPrChatSystemPrompt(
  input: AddressPrChatInput,
): string {
  return (
    `You are an expert software engineer helping the PR author address code review comments. The PR diff, reviewer comments, and fix plan are below.\n\n` +
    `${input.contextText}\n\n` +
    `The engineer is now conversing with you about the fix plan. Your role:\n` +
    `- Explain your reasoning for any proposed fix\n` +
    `- Revise a proposed fix if the engineer asks you to approach it differently\n` +
    `- When revising, describe the new approach clearly\n` +
    `- Be concise and direct — this is a conversation, not another report\n` +
    `- Do NOT produce JSON unless the engineer explicitly asks you to regenerate the full fix plan`
  );
}
